site_name: Nexus Instance Documentation
site_url: https://thenexusavenger.github.io/Nexus-Instance
repo_name: TheNexusAvenger/Nexus-Instance
repo_url: https://github.com/TheNexusAvenger/Nexus-Instance

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Why Nexus Instance: why-nexus-instance.md
  - Usage: 
    - Extending Classes: getting-started/extending-classes.md
    - Classes:
      - NexusObject: getting-started/classes/nexusobject.md
      - NexusInstance: getting-started/classes/nexusinstance.md
  - Contributing: contributing.md

markdown_extensions:
  - admonition